# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embeddings.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'embeddings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65mbeddings.proto\x12\nembeddings\"3\n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tnormalize\x18\x02 \x01(\x08\"e\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x02\"D\n\x0c\x42\x61tchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\x12\x11\n\tnormalize\x18\x03 \x01(\x08\"\x1b\n\tFloatList\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x88\x01\n\rBatchResponse\x12)\n\nembeddings\x18\x01 \x03(\x0b\x32\x15.embeddings.FloatList\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x05 \x01(\x02\"\x07\n\x05\x45mpty\"w\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\x08\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x1b\n\x13\x65mbedding_dimension\x18\x04 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\"\xe0\x01\n\rStatsResponse\x12\x17\n\x0finference_count\x18\x01 \x01(\x05\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x1b\n\x13\x65mbedding_dimension\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x1a\n\x12\x63pu_count_physical\x18\x05 \x01(\x05\x12\x19\n\x11\x63pu_count_logical\x18\x06 \x01(\x05\x12\x14\n\x0cram_total_gb\x18\x07 \x01(\x02\x12\x13\n\x0bram_used_gb\x18\x08 \x01(\x02\x12\x13\n\x0bram_percent\x18\t \x01(\x02\x32\xa2\x02\n\x10\x45mbeddingService\x12P\n\x11GenerateEmbedding\x12\x1c.embeddings.EmbeddingRequest\x1a\x1d.embeddings.EmbeddingResponse\x12\x44\n\rGenerateBatch\x12\x18.embeddings.BatchRequest\x1a\x19.embeddings.BatchResponse\x12<\n\x0bHealthCheck\x12\x11.embeddings.Empty\x1a\x1a.embeddings.HealthResponse\x12\x38\n\x08GetStats\x12\x11.embeddings.Empty\x1a\x19.embeddings.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=32
  _globals['_EMBEDDINGREQUEST']._serialized_end=83
  _globals['_EMBEDDINGRESPONSE']._serialized_start=85
  _globals['_EMBEDDINGRESPONSE']._serialized_end=186
  _globals['_BATCHREQUEST']._serialized_start=188
  _globals['_BATCHREQUEST']._serialized_end=256
  _globals['_FLOATLIST']._serialized_start=258
  _globals['_FLOATLIST']._serialized_end=285
  _globals['_BATCHRESPONSE']._serialized_start=288
  _globals['_BATCHRESPONSE']._serialized_end=424
  _globals['_EMPTY']._serialized_start=426
  _globals['_EMPTY']._serialized_end=433
  _globals['_HEALTHRESPONSE']._serialized_start=435
  _globals['_HEALTHRESPONSE']._serialized_end=554
  _globals['_STATSRESPONSE']._serialized_start=557
  _globals['_STATSRESPONSE']._serialized_end=781
  _globals['_EMBEDDINGSERVICE']._serialized_start=784
  _globals['_EMBEDDINGSERVICE']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
